# Type stub for the compiled extension, packaged by maturin with a py.typed marker. Checked
# against the built module by `python -m mypy.stubtest indrajala_math_rust` (CI), so a Rust
# signature change that isn't mirrored here fails the build.

from typing import Any, final, overload

from typing_extensions import Self

@final
class Array:
    def __new__(cls, data: list[float] | list[list[float]]) -> Array: ...
    @staticmethod
    def from_rows(rows: object) -> Array: ...
    @staticmethod
    def zeros(shape: int | tuple[int, int]) -> Array: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def T(self) -> Array: ...
    def row(self, i: int) -> Array: ...
    def take_rows(self, indices: list[int]) -> Array: ...
    @overload
    def __getitem__(self, index: tuple[slice, slice], /) -> Array: ...
    @overload
    def __getitem__(self, index: int | tuple[int, int], /) -> float: ...
    def __setitem__(self, index: int | tuple[int, int], value: float, /) -> None: ...
    def copy(self) -> Array: ...
    def tolist(self) -> Any: ...  # list[float] or list[list[float]], typed Any as numpy's ndarray.tolist is
    def reshape(self, shape: int | tuple[int, int]) -> Array: ...
    def __add__(self, other: Array | float, /) -> Array: ...
    def __sub__(self, other: Array | float, /) -> Array: ...
    def __rsub__(self, other: float, /) -> Array: ...
    def __mul__(self, other: Array | float, /) -> Array: ...
    def __rmul__(self, other: float, /) -> Array: ...
    def __truediv__(self, other: Array | float, /) -> Array: ...
    def __iadd__(self, other: Array | float, /) -> Self: ...
    def __isub__(self, other: Array | float, /) -> Self: ...
    def __matmul__(self, other: Array, /) -> Array: ...

@final
class ConvGeometry:
    def __new__(
        cls, input_height: int, input_width: int, input_channels: int, kernel_size: int, stride: int
    ) -> ConvGeometry: ...
    @property
    def input_height(self) -> int: ...
    @property
    def input_width(self) -> int: ...
    @property
    def input_channels(self) -> int: ...
    @property
    def kernel_size(self) -> int: ...
    @property
    def stride(self) -> int: ...
    @property
    def out_height(self) -> int: ...
    @property
    def out_width(self) -> int: ...
    @property
    def positions(self) -> int: ...
    @property
    def fan_in(self) -> int: ...
    @property
    def input_size(self) -> int: ...

def ping() -> str: ...
def set_matmul_threading(max_threads: int, threshold_flops: int) -> None: ...
def matmul_threads_for(m: int, k: int, n: int) -> int: ...
def outer(a: Array, b: Array) -> Array: ...
def exp(arr: Array) -> Array: ...
def sum_axis0(arr: Array) -> Array: ...
def argmax(arr: Array) -> int: ...
def array_relu(arr: Array) -> Array: ...
def array_relu_mask(downstream: Array, a: Array) -> Array: ...
def array_softmax(arr: Array) -> Array: ...
def uniform(low: float, high: float, shape: int | tuple[int, int]) -> Array: ...
def bernoulli_mask(drop_probability: float, shape: int | tuple[int, int]) -> Array: ...
def decode_mnist_pixels(data: bytes, record_size: int) -> Array: ...
def layer_forward(w: Array, x: Array, b: Array) -> Array: ...
def layer_forward_batch(w: Array, x: Array, b: Array) -> Array: ...
def layer_output_delta(a: Array, reference: Array) -> Array: ...
def layer_downstream(w: Array, delta: Array) -> Array: ...
def layer_downstream_batch(w: Array, delta_batch: Array) -> Array: ...
def layer_hidden_delta(next_w: Array, next_delta: Array, a: Array) -> Array: ...
def layer_hidden_delta_batch(next_w: Array, next_delta_batch: Array, a_batch: Array) -> Array: ...
def layer_accumulate_gradient(
    delta: Array, input_activation: Array, grad_w: Array, grad_b: Array
) -> tuple[Array, Array]: ...
def layer_accumulate_gradient_batch(
    delta_batch: Array, input_activation_batch: Array, grad_w: Array, grad_b: Array
) -> tuple[Array, Array]: ...
def layer_apply_accumulated_gradient(
    w: Array, b: Array, grad_w: Array, grad_b: Array, learning_rate: float, batch_size: int
) -> tuple[Array, Array]: ...
def layer_sgd_step(
    w: Array, b: Array, delta: Array, input_activation: Array, learning_rate: float
) -> tuple[Array, Array]: ...
def layer_adam_apply_accumulated_gradient(
    w: Array,
    b: Array,
    grad_w: Array,
    grad_b: Array,
    m_w: Array,
    v_w: Array,
    m_b: Array,
    v_b: Array,
    t: int,
    beta1: float,
    beta2: float,
    epsilon: float,
    learning_rate: float,
    batch_size: int,
) -> tuple[Array, Array, Array, Array, Array, Array]: ...
def layer_l2_apply_accumulated_gradient(
    w: Array, b: Array, grad_w: Array, grad_b: Array, l2_lambda: float, learning_rate: float, batch_size: int
) -> tuple[Array, Array]: ...
def layer_momentum_apply_accumulated_gradient(
    w: Array,
    b: Array,
    grad_w: Array,
    grad_b: Array,
    velocity_w: Array,
    velocity_b: Array,
    momentum: float,
    learning_rate: float,
    batch_size: int,
) -> tuple[Array, Array, Array, Array]: ...
def layer_relu_forward(w: Array, x: Array, b: Array) -> Array: ...
def layer_relu_forward_batch(w: Array, x: Array, b: Array) -> Array: ...
def layer_relu_hidden_delta(next_w: Array, next_delta: Array, a: Array) -> Array: ...
def layer_relu_hidden_delta_batch(next_w: Array, next_delta_batch: Array, a_batch: Array) -> Array: ...
def layer_softmax_forward(w: Array, x: Array, b: Array) -> Array: ...
def layer_softmax_forward_batch(w: Array, x: Array, b: Array) -> Array: ...
def layer_softmax_output_delta(a: Array, reference: Array) -> Array: ...
def layer_dropout_forward(
    w: Array, x: Array, b: Array, drop_probability: float, training: bool
) -> tuple[Array, Array, Array]: ...
def layer_dropout_forward_batch(
    w: Array, x: Array, b: Array, drop_probability: float, training: bool
) -> tuple[Array, Array, Array]: ...
def layer_dropout_hidden_delta(
    next_w: Array, next_delta: Array, base_activation: Array, mask: Array, keep_probability: float, was_training: bool
) -> Array: ...
def layer_dropout_hidden_delta_batch(
    next_w: Array,
    next_delta_batch: Array,
    base_activation_batch: Array,
    mask_batch: Array,
    keep_probability: float,
    was_training: bool,
) -> Array: ...
def conv_forward_batch(w: Array, x: Array, b: Array, geometry: ConvGeometry) -> tuple[Array, Array]: ...
def conv_downstream_batch(w: Array, delta_batch: Array, geometry: ConvGeometry) -> Array: ...
def conv_accumulate_gradient_batch(
    delta_batch: Array, cols: Array, grad_w: Array, grad_b: Array, geometry: ConvGeometry
) -> tuple[Array, Array]: ...
def max_pool_forward_batch(x: Array, geometry: ConvGeometry) -> tuple[Array, Array]: ...
def max_pool_downstream_batch(delta_batch: Array, argmax: Array, geometry: ConvGeometry) -> Array: ...
